// Vendor data for admin panel
// This includes all vendor information for management and display

export const VENDORS = [
  {
    id: 1,
    name: 'My Awesome Shop',
    owner: 'John Doe',
    ownerName: 'John Doe',
    status: 'Active',
    kycStatus: 'Verified',
    productCount: 45,
    state: 'Delhi',
    city: 'New Delhi',
    town: 'Central Delhi',
    tehsil: 'Connaught Place',
    subTehsil: 'CP',
    circle: 'North Circle',
    joinedDate: '2024-01-15',
    lastActive: '2 hours ago',
    category: 'Grocery',
    rating: 4.8,
    reviewCount: 12,
    contactNumber: '9876543210',
    email: 'john@example.com',
    address: 'Shop 12, Main Market',
    landmark: 'Near Clock Tower',
    pincode: '110001',
  },
  {
    id: 2,
    name: 'Quick Mart',
    owner: 'Jane Smith',
    ownerName: 'Jane Smith',
    status: 'Pending',
    kycStatus: 'Pending',
    productCount: 0,
    state: 'Maharashtra',
    city: 'Mumbai',
    town: 'Mumbai Suburban',
    tehsil: 'Andheri',
    subTehsil: 'Andheri East',
    circle: 'West Circle',
    joinedDate: '2024-12-20',
    lastActive: 'Never',
    category: 'General Store',
    rating: 0,
    reviewCount: 0,
    contactNumber: '9876543212',
    email: 'jane@example.com',
    address: 'Shop 5, Andheri Market',
    pincode: '400053',
  },
  {
    id: 3,
    name: 'City Groceries',
    owner: 'Raj Kumar',
    ownerName: 'Raj Kumar',
    status: 'Blocked',
    kycStatus: 'Verified',
    productCount: 120,
    state: 'Karnataka',
    city: 'Bangalore',
    town: 'Bangalore Urban',
    tehsil: 'Bangalore North',
    subTehsil: 'Hebbal',
    circle: 'South Circle',
    joinedDate: '2023-11-10',
    lastActive: '5 days ago',
    category: 'Groceries',
    rating: 4.2,
    reviewCount: 200,
    contactNumber: '9876543213',
    email: 'raj@example.com',
    address: 'Shop 20, Hebbal Market',
    pincode: '560024',
  },
  {
    id: 4,
    name: 'Fresh Market',
    owner: 'Priya Singh',
    ownerName: 'Priya Singh',
    status: 'Active',
    kycStatus: 'Verified',
    productCount: 78,
    state: 'Delhi',
    city: 'New Delhi',
    town: 'South Delhi',
    tehsil: 'Saket',
    subTehsil: 'Malviya Nagar',
    circle: 'South Circle',
    joinedDate: '2024-03-15',
    lastActive: '1 day ago',
    category: 'Groceries',
    rating: 4.3,
    reviewCount: 150,
    contactNumber: '9876543214',
    email: 'priya@example.com',
    address: 'Shop 8, Saket Market',
    pincode: '110017',
  },
  // New Grocery Vendors with Complete Details
  {
    id: 5,
    name: 'Daily Fresh Market',
    owner: 'Ramesh Kumar',
    ownerName: 'Ramesh Kumar',
    status: 'Active',
    kycStatus: 'Verified',
    productCount: 8,
    state: 'Uttar Pradesh',
    city: 'Noida',
    town: 'Gautam Buddha Nagar',
    tehsil: 'Sector 18',
    subTehsil: 'Sector 18 Market',
    circle: 'Noida Circle',
    joinedDate: '2019-01-10',
    lastActive: '30 minutes ago',
    category: 'Groceries',
    rating: 4.5,
    reviewCount: 120,
    distance: '0.5 km',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    isVerified: true,
    address: 'Shop No. 15, Sector 18 Market',
    landmark: 'Near Metro Station',
    pincode: '201301',
    geoLocation: { lat: 28.5700, lng: 77.3200 },
    contactNumber: '9876543210',
    alternateMobile: '9876543211',
    whatsappNumber: '9876543210',
    email: 'dailyfresh@example.com',
    yearsInBusiness: '5 Years',
    openTime: 'Open Now',
    openingTime: '07:00',
    closingTime: '22:00',
    weeklyOff: 'Sunday',
    about: 'Daily Fresh Market is your one-stop shop for all grocery needs. We offer fresh vegetables, fruits, dairy products, and daily essentials at competitive prices. With over 5 years of experience, we ensure quality products and excellent customer service.',
    products: [
      {
        id: 'g1p1',
        name: 'Basmati Rice (1kg)',
        price: '₹120',
        mrp: '₹140',
        category: 'Grains',
        stockQty: '150',
        imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80',
        description: 'Premium quality long grain basmati rice, perfect for biryani and pulao.',
        uom: 'Kg',
        brand: 'India Gate',
        isFastMoving: true,
        inStock: true
      },
      {
        id: 'g1p2',
        name: 'Toor Dal (1kg)',
        price: '₹95',
        mrp: '₹110',
        category: 'Pulses',
        stockQty: '200',
        imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc11e664f?auto=format&fit=crop&w=400&q=80',
        description: 'Fresh toor dal, rich in protein and essential nutrients.',
        uom: 'Kg',
        brand: 'Local',
        isFastMoving: true,
        inStock: true
      },
      {
        id: 'g1p3',
        name: 'Sunflower Oil (1L)',
        price: '₹145',
        mrp: '₹165',
        category: 'Cooking Oil',
        stockQty: '80',
        imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80',
        description: 'Refined sunflower oil, cholesterol-free and heart-healthy.',
        uom: 'Litre',
        brand: 'Fortune',
        isFastMoving: true,
        inStock: true
      },
      {
        id: 'g1p4',
        name: 'Tomato (1kg)',
        price: '₹40',
        mrp: '₹50',
        category: 'Vegetables',
        stockQty: '100',
        imageUrl: 'https://images.unsplash.com/photo-1546095667-0c4e01a98039?auto=format&fit=crop&w=400&q=80',
        description: 'Fresh, red, and juicy tomatoes, locally sourced.',
        uom: 'Kg',
        brand: 'Local',
        isFastMoving: true,
        inStock: true
      },
      {
        id: 'g1p5',
        name: 'Onion (1kg)',
        price: '₹35',
        mrp: '₹45',
        category: 'Vegetables',
        stockQty: '120',
        imageUrl: 'https://images.unsplash.com/photo-1518977822534-7049a61ee0c2?auto=format&fit=crop&w=400&q=80',
        description: 'Fresh onions, perfect for daily cooking needs.',
        uom: 'Kg',
        brand: 'Local',
        isFastMoving: true,
        inStock: true
      },
      {
        id: 'g1p6',
        name: 'Milk (1L)',
        price: '₹60',
        mrp: '₹65',
        category: 'Dairy',
        stockQty: '50',
        imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=400&q=80',
        description: 'Fresh, pure cow milk, delivered daily.',
        uom: 'Litre',
        brand: 'Amul',
        isFastMoving: true,
        inStock: true
      },
      {
        id: 'g1p7',
        name: 'Bread (400g)',
        price: '₹35',
        mrp: '₹40',
        category: 'Bakery',
        stockQty: '60',
        imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
        description: 'Fresh white bread, soft and delicious.',
        uom: 'Pack',
        brand: 'Britannia',
        isFastMoving: true,
        inStock: true
      },
      {
        id: 'g1p8',
        name: 'Sugar (1kg)',
        price: '₹45',
        mrp: '₹50',
        category: 'Sweeteners',
        stockQty: '90',
        imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=400&q=80',
        description: 'Pure white sugar, fine quality.',
        uom: 'Kg',
        brand: 'Madhur',
        isFastMoving: true,
        inStock: true
      }
    ],
    reviews: [
      {
        id: 'g1r1',
        userName: 'Rahul Sharma',
        rating: 5,
        date: '2 days ago',
        comment: 'Excellent quality products and very friendly staff. Prices are reasonable too!',
        reply: 'Thank you Rahul! We appreciate your feedback.'
      },
      {
        id: 'g1r2',
        userName: 'Priya Mehta',
        rating: 4,
        date: '1 week ago',
        comment: 'Good variety of products. Fresh vegetables and fruits. Will definitely shop again.',
        reply: null
      },
      {
        id: 'g1r3',
        userName: 'Amit Kumar',
        rating: 5,
        date: '2 weeks ago',
        comment: 'Best grocery store in the area. Always fresh products and good service.',
        reply: 'Thank you for your kind words, Amit!'
      },
      {
        id: 'g1r4',
        userName: 'Sneha Patel',
        rating: 4,
        date: '3 weeks ago',
        comment: 'Convenient location and good prices. Staff is helpful.',
        reply: null
      }
    ],
    offers: [
      {
        id: 'g1o1',
        title: 'Weekend Special',
        description: 'Get 10% off on all vegetables and fruits',
        code: 'VEG10',
        discountAmount: '10%',
        validUntil: '2025-12-31',
        isActive: true,
        color: 'bg-green-600'
      },
      {
        id: 'g1o2',
        title: 'First Order Discount',
        description: 'Flat ₹50 off on orders above ₹500',
        code: 'FIRST50',
        discountAmount: '₹50',
        validUntil: '2025-12-31',
        isActive: true,
        color: 'bg-orange-500'
      }
    ],
    enquiries: [
      {
        id: 'g1e1',
        senderName: 'Vikram Singh',
        senderMobile: '+91 9898989898',
        message: 'Do you have organic vegetables available?',
        date: '2024-12-20',
        status: 'new'
      },
      {
        id: 'g1e2',
        senderName: 'Anita Desai',
        senderMobile: '9797979797',
        message: 'What are your delivery charges?',
        date: '2024-12-19',
        status: 'read'
      }
    ]
  },
  {
    id: 6,
    name: 'Organic Harvest',
    owner: 'Meera Joshi',
    ownerName: 'Meera Joshi',
    status: 'Active',
    kycStatus: 'Verified',
    productCount: 10,
    state: 'Delhi',
    city: 'New Delhi',
    town: 'South Delhi',
    tehsil: 'Greater Kailash',
    subTehsil: 'M Block',
    circle: 'South Circle',
    joinedDate: '2016-03-20',
    lastActive: '1 hour ago',
    category: 'Groceries',
    rating: 4.8,
    reviewCount: 85,
    distance: '1.2 km',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    isVerified: true,
    address: 'Shop No. 42, Greater Kailash Part 1',
    landmark: 'Near M Block Market',
    pincode: '110048',
    geoLocation: { lat: 28.5500, lng: 77.2400 },
    contactNumber: '9876543220',
    alternateMobile: '9876543221',
    whatsappNumber: '9876543220',
    email: 'organicharvest@example.com',
    yearsInBusiness: '8 Years',
    openTime: 'Open Now',
    openingTime: '06:00',
    closingTime: '21:00',
    weeklyOff: 'Monday',
    about: 'Organic Harvest specializes in organic and natural products. We source directly from farmers to ensure the freshest organic produce. Our store offers a wide range of organic groceries, fruits, vegetables, grains, and health products. We are committed to promoting healthy living through organic food.',
    products: [
      {
        id: 'g2p1',
        name: 'Organic Brown Rice (1kg)',
        price: '₹180',
        mrp: '₹200',
        category: 'Grains',
        stockQty: '80',
        imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80',
        description: 'Certified organic brown rice, rich in fiber and nutrients.',
        uom: 'Kg',
        brand: 'Organic India',
        isFastMoving: true,
        inStock: true
      },
      {
        id: 'g2p2',
        name: 'Organic Moong Dal (500g)',
        price: '₹85',
        mrp: '₹95',
        category: 'Pulses',
        stockQty: '100',
        imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc11e664f?auto=format&fit=crop&w=400&q=80',
        description: 'Organic moong dal, pesticide-free and nutritious.',
        uom: 'Pack',
        brand: 'Organic India',
        isFastMoving: true,
        inStock: true
      },
      {
        id: 'g2p3',
        name: 'Cold Pressed Coconut Oil (500ml)',
        price: '₹350',
        mrp: '₹400',
        category: 'Cooking Oil',
        stockQty: '40',
        imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80',
        description: 'Pure cold-pressed coconut oil, unrefined and natural.',
        uom: 'Bottle',
        brand: 'Organic Harvest',
        isFastMoving: false,
        inStock: true
      },
      {
        id: 'g2p4',
        name: 'Organic Tomatoes (500g)',
        price: '₹60',
        mrp: '₹70',
        category: 'Vegetables',
        stockQty: '70',
        imageUrl: 'https://images.unsplash.com/photo-1546095667-0c4e01a98039?auto=format&fit=crop&w=400&q=80',
        description: 'Fresh organic tomatoes, grown without pesticides.',
        uom: 'Pack',
        brand: 'Local Organic',
        isFastMoving: true,
        inStock: true
      },
      {
        id: 'g2p5',
        name: 'Organic Spinach (250g)',
        price: '₹45',
        mrp: '₹55',
        category: 'Vegetables',
        stockQty: '50',
        imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=400&q=80',
        description: 'Fresh organic spinach, rich in iron and vitamins.',
        uom: 'Bunch',
        brand: 'Local Organic',
        isFastMoving: true,
        inStock: true
      },
      {
        id: 'g2p6',
        name: 'Organic Milk (500ml)',
        price: '₹80',
        mrp: '₹90',
        category: 'Dairy',
        stockQty: '60',
        imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=400&q=80',
        description: 'Pure organic cow milk, hormone-free and fresh.',
        uom: 'Pack',
        brand: 'Organic Valley',
        isFastMoving: true,
        inStock: true
      },
      {
        id: 'g2p7',
        name: 'Organic Honey (500g)',
        price: '₹450',
        mrp: '₹500',
        category: 'Sweeteners',
        stockQty: '30',
        imageUrl: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=400&q=80',
        description: 'Pure organic honey, raw and unprocessed.',
        uom: 'Jar',
        brand: 'Organic Harvest',
        isFastMoving: false,
        inStock: true
      },
      {
        id: 'g2p8',
        name: 'Organic Quinoa (500g)',
        price: '₹320',
        mrp: '₹350',
        category: 'Grains',
        stockQty: '25',
        imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80',
        description: 'Premium organic quinoa, high in protein and gluten-free.',
        uom: 'Pack',
        brand: 'Organic India',
        isFastMoving: false,
        inStock: true
      },
      {
        id: 'g2p9',
        name: 'Organic Turmeric Powder (200g)',
        price: '₹180',
        mrp: '₹200',
        category: 'Spices',
        stockQty: '45',
        imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=400&q=80',
        description: 'Pure organic turmeric powder, natural and chemical-free.',
        uom: 'Pack',
        brand: 'Organic Harvest',
        isFastMoving: true,
        inStock: true
      },
      {
        id: 'g2p10',
        name: 'Organic Green Tea (100g)',
        price: '₹250',
        mrp: '₹280',
        category: 'Beverages',
        stockQty: '35',
        imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=400&q=80',
        description: 'Premium organic green tea, rich in antioxidants.',
        uom: 'Pack',
        brand: 'Organic India',
        isFastMoving: false,
        inStock: true
      }
    ],
    reviews: [
      {
        id: 'g2r1',
        userName: 'Meera Joshi',
        rating: 5,
        date: '3 days ago',
        comment: 'Best organic store in the area! Quality products and knowledgeable staff. Highly recommended for health-conscious shoppers.',
        reply: 'Thank you Meera! We are glad you love our products.'
      },
      {
        id: 'g2r2',
        userName: 'Rajesh Verma',
        rating: 5,
        date: '1 week ago',
        comment: 'Amazing organic produce. Fresh, authentic, and worth every rupee. The vegetables are so fresh!',
        reply: 'Thank you for your trust in Organic Harvest!'
      },
      {
        id: 'g2r3',
        userName: 'Kavita Nair',
        rating: 4,
        date: '2 weeks ago',
        comment: 'Good variety of organic products. Prices are a bit high but quality is excellent.',
        reply: null
      },
      {
        id: 'g2r4',
        userName: 'Suresh Reddy',
        rating: 5,
        date: '3 weeks ago',
        comment: 'My go-to store for all organic needs. Staff is very helpful and products are always fresh.',
        reply: 'We appreciate your continued support, Suresh!'
      },
      {
        id: 'g2r5',
        userName: 'Divya Menon',
        rating: 4,
        date: '1 month ago',
        comment: 'Great selection of organic products. Love the fresh vegetables and organic dairy products.',
        reply: null
      }
    ],
    offers: [
      {
        id: 'g2o1',
        title: 'Organic Week',
        description: '15% off on all organic vegetables and fruits',
        code: 'ORG15',
        discountAmount: '15%',
        validUntil: '2025-12-31',
        isActive: true,
        color: 'bg-green-600'
      },
      {
        id: 'g2o2',
        title: 'Health Package',
        description: 'Buy 3 organic products, get 1 free (lowest value)',
        code: 'HEALTH3',
        discountAmount: 'Free Item',
        validUntil: '2025-12-31',
        isActive: true,
        color: 'bg-purple-600'
      }
    ],
    enquiries: [
      {
        id: 'g2e1',
        senderName: 'Neha Kapoor',
        senderMobile: '+91 9688888888',
        message: 'Do you have organic quinoa in stock?',
        date: '2024-12-20',
        status: 'replied'
      },
      {
        id: 'g2e2',
        senderName: 'Arjun Malhotra',
        senderMobile: '9677777777',
        message: 'What are your store timings on weekends?',
        date: '2024-12-19',
        status: 'read'
      }
    ]
  }
];

// Helper function to get vendor by ID
export const getVendorById = (id) => {
  return VENDORS.find(vendor => vendor.id === id);
};

// Helper function to get vendors by category
export const getVendorsByCategory = (category) => {
  return VENDORS.filter(vendor => vendor.category === category);
};

// Helper function to get vendors by status
export const getVendorsByStatus = (status) => {
  return VENDORS.filter(vendor => vendor.status === status);
};
